# misc
home:
    pattern:  /
    defaults: { _controller: IhswLedgerBundle:Default:index }
    options:
        expose: true

# items
items:
    pattern: /items
    defaults: { _controller: IhswLedgerBundle:Item:index }
    methods: [GET]
    options:
        expose: true
item_create:
    pattern: /items
    defaults: { _controller: IhswLedgerBundle:Item:create }
    methods: [POST]
    options:
        expose: true
item_delete:
    pattern: /item/{itemId}
    defaults: { _controller: IhswLedgerBundle:Item:destroy }
    methods: [DELETE]
    options:
        expose: true
item_show:
    pattern: /item/{itemId}
    defaults: { _controller: IhswLedgerBundle:Item:show }
    methods: [GET]
    options:
        expose: true
item_update:
    pattern: /item/{itemId}
    defaults: { _controller: IhswLedgerBundle:Item:update }
    methods: [PUT]
    options:
        expose: true

# entries
entries:
    pattern: /entries
    defaults: { _controller: IhswLedgerBundle:Entry:index }
    methods: [GET]
    options:
        expose: true
entry_create:
    pattern: /entries
    defaults: { _controller: IhswLedgerBundle:Entry:create }
    methods: [POST]
    options:
        expose: true
entry_delete:
    pattern: /entry/{entryId}
    defaults: { _controller: IhswLedgerBundle:Entry:destroy }
    methods: [DELETE]
    options:
        expose: true
entry_show:
    pattern: /entry/{entryId}
    defaults: { _controller: IhswLedgerBundle:Entry:show }
    methods: [GET]
    options:
        expose: true

# entryitems
entryitem_create:
    pattern: /entry/{entryId}/entryitems
    defaults: { _controller: IhswLedgerBundle:EntryItem:create }
    methods: [POST]
    options:
        expose: true
entryitem_delete:
    pattern: /entryitem/{entryItemId}
    defaults: { _controller: IhswLedgerBundle:EntryItem:destroy }
    methods: [DELETE]
    options:
        expose: true