parameters:
#    ihsw_ledger.example.class: Ihsw\LedgerBundle\Example

services:
#    ihsw_ledger.example:
#        class: %ihsw_ledger.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
